# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LjwDPdwQubsgLv8ic8IiKQMmC2hwZukP
"""

import json
import base64
import matplotlib
# Configura o backend 'Agg' para funcionar em servidor sem monitor
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
from fastapi.responses import StreamingResponse

app = FastAPI()

# --- MODELO DE DADOS QUE VEM DO N8N ---
class ItemList(BaseModel):
    itens: List[Dict[str, Any]]
    titulo_simulado: Optional[str] = "SIMULADO SAEB"

# --- MOTOR GRÁFICO (MATPLOTLIB) ---
def gerar_matplotlib(categoria, dados):
    fig, ax = plt.subplots(figsize=(6, 3.5), dpi=150)
    ax.set_axis_off()

    try:
        if categoria == "GRAFICO_BARRAS":
            ax.set_axis_on()
            colors = ['#5DADE2', '#F4D03F', '#AF7AC5', '#EC7063']
            valores = dados.get('valores', [])
            labels = dados.get('labels', [])
            # Garante que as barras existam
            if valores and labels:
                bars = ax.bar(labels, valores, color=colors[:len(labels)], edgecolor='black')
                ax.bar_label(bars, padding=3)
                ax.set_title(dados.get('titulo', ''), fontsize=10, fontweight='bold')
                ax.set_ylabel(dados.get('eixo_y', ''))
                ax.spines['top'].set_visible(False)
                ax.spines['right'].set_visible(False)

        elif categoria == "TABELA":
            if dados.get("tipo") == "grid_coordenadas":
                ax.set_aspect('equal'); ax.set_xlim(0, 3); ax.set_ylim(0, 3)
                # Grade 2x2
                ax.plot([1, 3], [1, 1], 'k-', lw=2); ax.plot([1, 3], [0, 0], 'k-', lw=2); ax.plot([1, 3], [2, 2], 'k-', lw=2)
                ax.plot([1, 1], [0, 2], 'k-', lw=2); ax.plot([2, 2], [0, 2], 'k-', lw=2); ax.plot([3, 3], [0, 2], 'k-', lw=2)
                # Labels
                ax.text(1.5, 2.3, "A", ha='center', fontweight='bold'); ax.text(2.5, 2.3, "B", ha='center', fontweight='bold')
                ax.text(0.5, 1.5, "1", ha='center', fontweight='bold'); ax.text(0.5, 0.5, "2", ha='center', fontweight='bold')
                # Objeto
                pos = dados.get('posicao', 'B2')
                coords = {'A1': (1.5, 1.5), 'B1': (2.5, 1.5), 'A2': (1.5, 0.5), 'B2': (2.5, 0.5)}
                x, y = coords.get(pos, (2.5, 0.5))
                ax.text(x, y, "★", ha='center', va='center', fontsize=30, color='#F39C12')
            else:
                col_labels = dados.get("colunas", ["A", "B"])
                cell_text = dados.get("linhas", [["-", "-"]])
                table = ax.table(cellText=cell_text, colLabels=col_labels, loc='center', cellLoc='center')
                table.auto_set_font_size(False); table.set_fontsize(11); table.scale(1, 1.5)

        elif categoria == "RETA_NUMERICA":
            inicio, fim = dados.get('inicio', 0), dados.get('fim', 10)
            ax.set_ylim(0, 3); ax.set_xlim(inicio-1, fim+1)
            ax.plot([inicio, fim], [1.5, 1.5], 'k-', lw=2) # Linha principal
            passo = dados.get('passo', 1)
            for i in range(inicio, fim + 1):
                ax.plot([i, i], [1.3, 1.7], 'k-', lw=2) # Ticks
                if i == dados.get('escondido'):
                    ax.add_patch(patches.Rectangle((i-0.3, 1.8), 0.6, 0.6, facecolor='#F1C40F'))
                    ax.text(i, 2.1, "?", ha='center', va='center', fontweight='bold')
                elif (i - inicio) % passo == 0:
                    ax.text(i, 1.0, str(i), ha='center', fontsize=10)
            if 'seta_inicio' in dados:
                s_ini = dados['seta_inicio']; s_fim = dados['seta_fim']
                arrow = patches.FancyArrowPatch((s_ini, 1.5), (s_fim, 1.5), connectionstyle="arc3,rad=.3", arrowstyle='Simple, tail_width=0.5, head_width=4, head_length=8', color="#E74C3C")
                ax.add_patch(arrow)

        elif categoria == "RELOGIO_DIGITAL":
            ax.set_aspect('equal'); ax.set_xlim(0, 10); ax.set_ylim(0, 4)
            # Verifica se é lista de horas ou hora única
            horas = []
            if "hora" in dados: horas.append(dados["hora"])
            if "hora_inicio" in dados: horas = [dados["hora_inicio"], dados["hora_fim"]]

            start_x = (10 - (len(horas) * 3.5)) / 2
            for i, h in enumerate(horas):
                x_pos = start_x + i * 4.0
                ax.add_patch(patches.Rectangle((x_pos, 1.2), 3.2, 1.6, facecolor='black', edgecolor='gray', lw=3))
                ax.text(x_pos + 1.6, 2.0, h, ha='center', va='center', color='#00FF00', fontsize=20, fontfamily='monospace', fontweight='bold')

        elif categoria == "BLOCOS_LOGICOS":
            ax.set_aspect('equal'); ax.set_xlim(0, 10); ax.set_ylim(0, 4)
            tipo = dados.get("tipo", "generico")

            if tipo == "material_dourado":
                dezenas, unidades = int(dados.get("dezenas", 0)), int(dados.get("unidades", 0))
                total_w = (dezenas * 0.7) + 0.5 + (unidades * 0.5)
                start_x = (10 - total_w) / 2
                for i in range(dezenas):
                    rect = patches.Rectangle((start_x + i*0.7, 1), 0.5, 3, facecolor='#F39C12', edgecolor='black')
                    ax.add_patch(rect)
                    for j in range(1, 10): ax.plot([start_x+i*0.7, start_x+i*0.7+0.5], [1+j*0.3, 1+j*0.3], 'k-', lw=0.5)
                u_start = start_x + (dezenas * 0.7) + 0.5
                for k in range(unidades):
                    rect = patches.Rectangle((u_start + (k%5)*0.6, 1 + (k//5)*0.6), 0.4, 0.4, facecolor='#F39C12', edgecolor='black')
                    ax.add_patch(rect)
            # Adicione aqui os outros tipos (Dinheiro, Sequencia) se necessário, seguindo o padrão anterior

    except Exception as e:
        ax.text(0.5, 0.5, "Erro Visual", ha='center', color='red')

    img_buffer = BytesIO()
    plt.tight_layout()
    plt.savefig(img_buffer, format='png', bbox_inches='tight')
    plt.close(fig)
    img_buffer.seek(0)
    return img_buffer

# --- MOTOR DE WORD ---
def criar_word_prova(data):
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Arial'; style.font.size = Pt(11)

    # Cabeçalho
    p_head = doc.add_paragraph()
    p_head.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run_h = p_head.add_run(f"{data.titulo_simulado}")
    run_h.bold = True; run_h.font.size = Pt(14)
    doc.add_paragraph("_" * 70)
    doc.add_paragraph("Nome: _________________________________________________ Data: ___/___/___")
    doc.add_paragraph("_" * 70)

    for i, item in enumerate(data.itens):
        # Questão
        p_q = doc.add_paragraph()
        run_q = p_q.add_run(f"QUESTÃO {i+1} ")
        run_q.bold = True
        # Descritor discreto
        run_desc = p_q.add_run(f"({item.get('descritor_codigo', '')} - {item.get('nivel_dificuldade', '')})")
        run_desc.font.size = Pt(8); run_desc.font.color.rgb = RGBColor(100,100,100)

        doc.add_paragraph(item.get('enunciado', ''))

        # IMAGEM
        tipo_vis = item.get('tipo_visual_categoria', 'NENHUM')
        img_stream = None

        # 1. Matplotlib
        if tipo_vis == 'MATPLOTLIB' and item.get('dados_visual_python'):
            img_stream = gerar_matplotlib(tipo_vis, item['dados_visual_python'])

        # 2. IA Generativa (Vem do n8n em Base64 na propriedade 'imagem_base64')
        elif tipo_vis == 'IA_GENERATIVA' and item.get('imagem_base64'):
            try:
                # Decodifica Base64
                image_data = base64.b64decode(item['imagem_base64'])
                img_stream = BytesIO(image_data)
            except Exception as e:
                print(f"Erro imagem IA: {e}")

        if img_stream:
            doc.add_picture(img_stream, width=Inches(4.0))
            doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph("") # Espaço

        # Alternativas
        letras = ['a', 'b', 'c', 'd', 'e']
        alts = item.get('alternativas', {})
        table = doc.add_table(rows=len(alts), cols=1)
        for idx, l in enumerate(letras):
            if l in alts:
                table.cell(idx, 0).text = f"({l.upper()}) {alts[l]}"

        doc.add_paragraph("-" * 50)

    # Gabarito
    doc.add_page_break()
    doc.add_heading("GABARITO E JUSTIFICATIVAS", 0)
    for i, item in enumerate(data.itens):
        p = doc.add_paragraph()
        p.add_run(f"Q{i+1}: Gabarito {item.get('gabarito', '').upper()}").bold = True
        justs = item.get('justificativa_pedagogica', {})
        if not justs: justs = item.get('justificativa_alternativas', {})

        for l in letras:
            if l in justs:
                doc.add_paragraph(f"{l.upper()}) {justs[l]}", style='List Bullet')
        doc.add_paragraph("")

    file_stream = BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream

@app.post("/gerar-simulado")
async def api_endpoint(data: ItemList):
    try:
        arquivo = criar_word_prova(data)
        return StreamingResponse(
            arquivo,
            media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            headers={"Content-Disposition": "attachment; filename=simulado_saeb.docx"}
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))